# Generated by Django 4.0.3 on 2022-06-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPersona',
            fields=[
                ('nombre', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Rut')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('contraseña', models.CharField(max_length=30, verbose_name='Contraseña')),
                ('conficontraseña', models.CharField(max_length=30, verbose_name='Confirmar Contraseña')),
                ('genero', models.CharField(max_length=20, verbose_name='Género')),
                ('suscripcion', models.CharField(max_length=20, verbose_name='Suscripción')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
        ),
    ]
