# Generated by Django 4.0.3 on 2022-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registropersona_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('boleta', models.IntegerField(primary_key=True, serialize=False, verbose_name='Boleta')),
                ('fecha_compra', models.CharField(max_length=50, verbose_name='Fecha Compra')),
                ('rut', models.CharField(max_length=30, verbose_name='Rut')),
                ('email', models.CharField(max_length=60, verbose_name='Email')),
                ('producto', models.CharField(max_length=40, verbose_name='Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad de Productos')),
                ('metodo', models.CharField(max_length=30, verbose_name='Metodo de pago')),
                ('tarjeta', models.CharField(max_length=80, verbose_name='Tarjeta')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha de expiración')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('total', models.IntegerField(verbose_name='Total de Boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productonombre', models.CharField(max_length=40, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
